### ISSUE TITLE
Popup window stuck in callback

### ISSUE THREAD

**Issue by pdrbrnd** [marksteele/netlify-serverless-oauth2-backend#2]
Hi,

First of all, thanks for this.
We must be doing something wrong, so let me apologise beforehand for bothering you with this.

I see you have an Issue opened at netlify-cms's repo (https://github.com/netlify/netlify-cms/issues/1285) with the exact same problem. I was wondering how did you managed to solve it?

Our auth popup window just hangs with the callback URL even tho our API Gateway endpoint is returning the correct response (with the correct `postMessage` 'authorization:github:success:{"token":TOKEN ...)

**Comment by marksteele** [comment]
I'm not sure where things are going wrong for you. The issue I had opened got fixed by allowing to set the auth_endpoint in the netlify config. 

Blog post with my setup: https://www.control-alt-del.org/post/serverless-blog-howto

If you want to see the output of the blog (as generated from running hugo), it's here: https://github.com/marksteele/marksteele.github.io

(check out the /admin folder for the netflify config)

The repo for the source is here: https://github.com/marksteele/blog

It's running fine for me with version 1.9.2

The only difference I can think of between the blog post and my live setup is that I'm remapping urls in cloudfront, but that was just a style thing, I had it working as described in the blog before I had remapped them.

**Comment by ArcaneTSGK** [comment]
@pbrandone Did you manage to solve your issue with the popup window?

**Comment by pdrbrnd** [comment]
@ArcaneTSGK sorry for the delay. Apparently it was only a permissions issue with Github. Make sure you have granted the correct permissions when authorising the app. In my case I had previously auth'ed with my personal account and then things got a bit messed up on the Org's private repo
